services:
  web:
    build: .
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:  # Mount local project for "live code changes" (overrides "image", "bypasses .dockerignore", "forces poetry run")
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db
  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    # env_file:
    #   - .env.dev.db
    environment:
      - POSTGRES_USER=config_django
      - POSTGRES_PASSWORD=config_django
      - POSTGRES_DB=config_django_dev

volumes:
  postgres_data:
